name: ai
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pytorch
  - pyvista
  - vtk
  - gmsh
  - meshio
  - pydantic
  - pytest
  - gymnasium
  - opencv
  - matplotlib
  - pandas
  - pip
